
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sonan
 */
public class Form extends javax.swing.JFrame {
    public SinhVienATTT sinhvienAT;
    public SinhVienMatMa sinhvienMM;

    /**
     * Creates new form form
     */
    public Form() {
        initComponents();
    }

    public boolean KiemTraRongSVAT() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("") || tfNgaysinh.getText().equals("") || tfDTB.getText().equals("") || tfHocphi.getText().equals("") || (!nam.isSelected() && !nu.isSelected())) {
            return true;
        }
        return false;
    }

    public boolean KiemTraRongSVMM() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("") || tfNgaysinh.getText().equals("") || tfDTB.getText().equals("") || tfDonvi.getText().equals("") || tfLuong.getText().equals("") || (!nam.isSelected() && !nu.isSelected())) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        svat = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        svmm = new javax.swing.JRadioButton();
        tfMasv = new javax.swing.JTextField();
        tfHoten = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        tfNgaysinh = new javax.swing.JTextField();
        tfDTB = new javax.swing.JTextField();
        tfHocphi = new javax.swing.JTextField();
        tfDonvi = new javax.swing.JTextField();
        tfLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nam = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        nu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Don vi");

        buttonGroup1.add(svat);
        svat.setText("SVATTT");
        svat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svatActionPerformed(evt);
            }
        });

        jLabel10.setText("Luong");

        buttonGroup1.add(svmm);
        svmm.setText("SVMM");
        svmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmmActionPerformed(evt);
            }
        });

        save.setText("Luu Sinh Vien");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        tfNgaysinh.setToolTipText("");

        tfHocphi.setToolTipText("");

        jLabel1.setText("Form nhap thong tin");

        jLabel2.setText("Ma SV");

        jLabel3.setText("Ho ten");

        jLabel4.setText("Ngay sinh");

        jLabel5.setText("Gioi tinh");

        jLabel6.setText("Diem TB");

        jLabel7.setText("Loai SV");

        nam.setText("Nam");

        jLabel8.setText("Hoc phi");

        nu.setText("Nu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nu))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(svat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(svmm, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfLuong)
                            .addComponent(tfDonvi)
                            .addComponent(tfHocphi)
                            .addComponent(tfDTB)
                            .addComponent(tfNgaysinh)
                            .addComponent(tfHoten)
                            .addComponent(tfMasv))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(svat)
                    .addComponent(svmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nam)
                    .addComponent(nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(save)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void svatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svatActionPerformed
        tfDonvi.setEnabled(false);
        tfDonvi.setText("");
        tfLuong.setEnabled(false);
        tfLuong.setText("");
        tfHocphi.setEnabled(true);
    }//GEN-LAST:event_svatActionPerformed

    private void svmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmmActionPerformed
        tfHocphi.setEnabled(false);
        tfHocphi.setText("");
        tfDonvi.setEnabled(true);
        tfLuong.setEnabled(true);
    }//GEN-LAST:event_svmmActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (!svat.isSelected() && !svmm.isSelected()) {
            JOptionPane.showMessageDialog(null, "vui long chon loai SV");
            return;
        }
        if (svat.isSelected()) {
            if (KiemTraRongSVAT() == true) {
                JOptionPane.showMessageDialog(null, "chua du thong tin");
            } else {
                try {
                    Float.parseFloat(tfDTB.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "vui long nhap so");
                    return;
                }
                Float dtb = Float.parseFloat(tfDTB.getText());
                if (dtb > 10 || dtb < 0) {
                    JOptionPane.showMessageDialog(null, "ban phai nhap diem trung binh 0 -> 10");
                    return;
                }
                try {
                    Float.parseFloat(tfHocphi.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "vui long nhap so");
                    return;
                }
                sinhvienAT = new SinhVienATTT(tfMasv.getText(), tfHoten.getText(), tfNgaysinh.getText(),
                        nam.isSelected() ? "nam" : "nu", dtb, Float.parseFloat(tfHocphi.getText()));
                try {
                    FileWriter fw = new FileWriter("svat.dat", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(sinhvienAT.toString());
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "luu thanh cong");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "luu that bai");
                }
            }
        } else if (svmm.isSelected()) {
            if (KiemTraRongSVMM() == true) {
                JOptionPane.showMessageDialog(null, "chua du thong tin");
                return;
            } else {
                try {
                    Float.parseFloat(tfDTB.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "vui long nhap so");
                    return;
                }
                Float dtb = Float.parseFloat(tfDTB.getText());
                if (dtb > 10 || dtb < 0) {
                    JOptionPane.showMessageDialog(null, "ban phai nhap diem trung binh 0 -> 10");
                    return;
                }
                try {
                    Float.parseFloat(tfLuong.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "vui long nhap so");
                    return;
                }

                sinhvienMM = new SinhVienMatMa(tfMasv.getText(), tfHoten.getText(),
                        tfNgaysinh.getText(), nam.isSelected() ? "nam" : "nu", dtb, tfDonvi.getText(),
                        Float.parseFloat(tfLuong.getText()));
                try {
                    FileWriter fw = new FileWriter("svmm.dat", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(sinhvienMM.toString());
                    bw.newLine();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "luu thanh cong");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "luu that bai");
                }
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the Form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton svat;
    private javax.swing.JRadioButton svmm;
    private javax.swing.JTextField tfDTB;
    private javax.swing.JTextField tfDonvi;
    private javax.swing.JTextField tfHocphi;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMasv;
    private javax.swing.JTextField tfNgaysinh;
    // End of variables declaration//GEN-END:variables
}
