
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.StyledEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sonan
 */
public class Form extends javax.swing.JFrame {

    ArrayList<ThiSinh> list = new ArrayList<>();
    ThiSinhKhoiA tsa;
    ThiSinhKhoiC tsc;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();

    }

    public boolean validateForm() {
        if (diem1.getText().equals("") || diem2.getText().equals("") || diem3.getText().equals("") || hoten.getText().equals("") || ngaysinh.getText().equals("") || diachi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin");
            return false;
        } else if (!validateDiem()) {
            JOptionPane.showMessageDialog(this, "nhap diem la so tu 1 den 10");
            return false;
        } else if(!kiemTra(hoten.getText())) {
            JOptionPane.showMessageDialog(this, "thi sinh nay da ton tai");
            return false;
        }
        else {
            return true;
        }
    }

    public boolean validateDiem() {
        try {
            float a = Float.parseFloat(diem1.getText());
            float b = Float.parseFloat(diem2.getText());
            float c = Float.parseFloat(diem3.getText());
            if (a < 0 || a > 10 || b < 0 || b > 10 || c < 0 || c > 10) {
                return false;
            }
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public boolean kiemTra(String name) {
        for (ThiSinh thiSinh : list) {
            if (thiSinh.getHoTen().equals(name)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        ngaysinh = new javax.swing.JTextField();
        hoten = new javax.swing.JTextField();
        diachi = new javax.swing.JTextField();
        t3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        khoi = new javax.swing.JComboBox<>();
        diem3 = new javax.swing.JTextField();
        diem2 = new javax.swing.JTextField();
        diem1 = new javax.swing.JTextField();
        hienthi = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhap thong tin thi sinh");

        jLabel1.setText("Ho ten");

        jLabel2.setText("Ngay sinh");

        jLabel3.setText("Dia chi");

        t1.setText("Diem toan");

        t2.setText("Diem ly");

        t3.setText("Diem hoa");

        jLabel7.setText("Khoi");

        khoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoi A", "Khoi C" }));
        khoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khoiActionPerformed(evt);
            }
        });

        hienthi.setText("hien thi");
        hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiActionPerformed(evt);
            }
        });

        save.setText("luu");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(t3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(t2)
                    .addComponent(t1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diem2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(diem1)
                                .addComponent(diem3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hoten)
                            .addComponent(diachi)
                            .addComponent(khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(hienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hienthi)
                    .addComponent(save))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            if (khoi.getSelectedIndex() == 0) {
                float a = Float.parseFloat(diem1.getText());
                float b = Float.parseFloat(diem2.getText());
                float c = Float.parseFloat(diem3.getText());
                tsa = new ThiSinhKhoiA(hoten.getText(), ngaysinh.getText(), diachi.getText(), a, b, c);
                list.add(tsa);
                JOptionPane.showMessageDialog(this, "them thanh cong");
            } else {
                float a = Float.parseFloat(diem1.getText());
                float b = Float.parseFloat(diem2.getText());
                float c = Float.parseFloat(diem3.getText());
                tsc = new ThiSinhKhoiC(hoten.getText(), ngaysinh.getText(), diachi.getText(), a, b, c);
                list.add(tsc);
                JOptionPane.showMessageDialog(this, "them thanh cong");
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void khoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khoiActionPerformed
        // TODO add your handling code here:
        if (khoi.getSelectedIndex() == 0) {
            t1.setText("Mon toan");
            t2.setText("Mon ly");
            t3.setText("Mon hoa");
        } else {
            t1.setText("Mon van");
            t2.setText("Mon su");
            t3.setText("Mon dia");
        }
    }//GEN-LAST:event_khoiActionPerformed

    private void hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiActionPerformed
        // TODO add your handling code here:
        int stt1 = 1, stt2 = 1;
        System.out.println("Danh sach thi sinh trung tuyen khoi A la: ");
        System.out.println("--------------------------------");
        System.out.println("STT" + "\t" + "ten thi sinh" + "\t" + "Tong diem");
        for (ThiSinh thiSinh : list) {
            if (thiSinh.getClass().getName().equals("ThiSinhKhoiA") && thiSinh.getTongDiem() > 20) {
                System.out.println(stt1 + "\t" + thiSinh.getHoTen() + "\t\t" + thiSinh.getTongDiem());
            }
        }
        System.out.println("=================================");
        System.out.println("Danh sach thi sinh trung tuyen khoi C la: ");
        System.out.println("---------------------------------");
        System.out.println("STT" + "\t" + "ten thi sinh" + "\t" + "Tong diem");
        for (ThiSinh thiSinh : list) {
            if (thiSinh.getClass().getName().equals("ThiSinhKhoiC") && thiSinh.getTongDiem() > 20) {
                System.out.println(stt2 + "\t" + thiSinh.getHoTen() + "\t\t" + thiSinh.getTongDiem());
            }
        }
    }//GEN-LAST:event_hienthiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField diem1;
    private javax.swing.JTextField diem2;
    private javax.swing.JTextField diem3;
    private javax.swing.JButton hienthi;
    private javax.swing.JTextField hoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> khoi;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JButton save;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    // End of variables declaration//GEN-END:variables
}
